package jdbc;

public class Problem {
    private int id;
    private String title;
    private String description;
    private String difficulty;

    // Constructor for SAVING (ID is auto-generated by DB, so we don't need it here)
    public Problem(String title, String description, String difficulty) {
        this.title = title;
        this.description = description;
        this.difficulty = difficulty;
    }

    // Constructor for FETCHING (We get ID from DB)
    public Problem(int id, String title, String description, String difficulty) {
        this.id = id;
        this.title = title;
        this.description = description;
        this.difficulty = difficulty;
    }

    // Getters
    public String getTitle() { return title; }
    public String getDescription() { return description; }
    public String getDifficulty() { return difficulty; }

    // Pretty print for console
    public String toString() {
        return "Problem #" + id + ": " + title + " (" + difficulty + ")";
    }
}